variable "APP_KEYS" {}
variable "API_TOKEN_SALT" {}
variable "ADMIN_JWT_SECRET" {}
variable "TRANSFER_TOKEN_SALT" {}
variable "ENCRYPTION_KEY" {}
variable "JWT_SECRET" {}
variable "DATABASE_NAME" {}
variable "DATABASE_USERNAME" {}
variable "DATABASE_PASSWORD" {}
variable "ecs_executation_role" {}
variable "ecr_image" {}
